# Generated by Django 4.0.4 on 2022-04-30 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
