# Generated by Django 4.0.4 on 2022-04-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coins.coin'),
        ),
    ]
