# Generated by Django 4.0.4 on 2022-04-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_alter_userwallet_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='get_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
